# Generated by Django 5.2.5 on 2025-09-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rpm', models.FloatField()),
                ('motor_power', models.FloatField()),
                ('outlet_pressure_bar', models.FloatField()),
                ('air_flow', models.FloatField()),
                ('noise_db', models.FloatField()),
                ('outlet_temp', models.FloatField()),
                ('gaccx', models.FloatField()),
                ('gaccy', models.FloatField()),
                ('gaccz', models.FloatField()),
                ('haccx', models.FloatField()),
                ('haccy', models.FloatField()),
                ('haccz', models.FloatField()),
                ('exvalve', models.IntegerField()),
                ('acmotor', models.IntegerField()),
                ('status_qualidade', models.CharField(default='Não Analisado', max_length=50)),
                ('diagnostico', models.CharField(default='Análise pendente', max_length=200)),
            ],
        ),
    ]
