# Generated by Django 5.2.5 on 2025-09-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='acmotor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='exvalve',
            field=models.IntegerField(default=0),
        ),
    ]
