# Generated by Django 5.2.5 on 2025-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0002_alter_compressor_acmotor_alter_compressor_exvalve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='diagnostico',
            field=models.CharField(default='Análise pendente', max_length=500),
        ),
    ]
