# Generated by Django 5.2.5 on 2025-09-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0003_alter_compressor_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='status_qualidade',
            field=models.CharField(default='Não analisado', max_length=20),
        ),
    ]
